In [1]:
import torch

In [21]:
a = torch.randn(5, 3)

In [41]:
u, s, vh = torch.linalg.svd(a, full_matrices = False)

In [42]:
u

tensor([[-0.3650, -0.5585, -0.3594],
        [ 0.3260,  0.4068, -0.5835],
        [-0.1405, -0.5407, -0.0828],
        [-0.0764,  0.0173, -0.7235],
        [ 0.8573, -0.4795, -0.0092]])

In [43]:
vh

tensor([[ 0.8845,  0.3809, -0.2693],
        [ 0.4313, -0.8878,  0.1608],
        [-0.1778, -0.2584, -0.9495]])

In [44]:
s

tensor([2.7794, 1.2683, 0.5402])

In [45]:
torch.dist(a, torch.mm(torch.mm(u, torch.diag(s)), vh))

tensor(9.1713e-07)

In [35]:
u[:,:2]

tensor([[-0.3650, -0.5585],
        [ 0.3260,  0.4068],
        [-0.1405, -0.5407],
        [-0.0764,  0.0173],
        [ 0.8573, -0.4795]])

In [36]:
torch.dist(a, torch.mm(torch.mm(u[:,:2], torch.diag(s[:2])), vh[:2,:]))

tensor(0.5402)