Introduction to Pytorch Tensors
===============================

Pytorch is an optimised `tensor` manipulation library that offers an array of packages for deep learning. As compared to static frameworks such as Theano, Caffe and Tensorflow, Pytorch is in the family of dynamic frameworks, which does not require pre-defined computational graphs. This allows for a more flexible, imperative style of development, as it does not require the computational graphs to be first declared, compiled, and then excuted. However, this is potentially at the cost of computational efficiency, which makes it not as advantageous for production and mobile settings, but extremely useful during research and development.

```{image} ../images/nlp_pytorch_book.jpg
:alt: Pytorch for NLP Book
:class: bg-primary mb-1
:width: 200px
:align: left
```
```{image} ../images/logo_pytorch.jpeg
:alt: Pytorch Logo
:class: bg-primary mb-1
:width: 100px
:align: right
```
Reference: *Natural Lanuage Processing with PyTorch* - Building intelligent lanaguage applications using deep learning, by Delip Rao and Brian McMahan (copyright O'REILLY Feb 2019)

## Tensors

```{admonition} Tensor
A tensor is a mathematical object holding some multidimensional data. 
```

```{image} ../images/tensor.png
:alt: Tensors
:class: bg-primary mb-1
:width: 80%
:align: center
```
* A tensor of order zero is just a number, or a `scalar`.
* A tensor of order one (1st-order tensor) is an array of numbers, or a `vector`.
* A tensor of order two (2nd-order tensor) is an array of vectors, or a `matrix`.
* A tenosr of order n (nth-order tensor) is a generalised n-dimensional array of scalars. 

## Creating Tensors

### A helper function `describe(x)`
`x` is a torch tensor

NOTE: `tensor.shape` is a property, not a callable function

In [7]:
def describe(x):
    print("Type:{}".format(x.type()))
    print("Shape/size:{}".format(x.shape))
    print("Values: \n{}".format(x))


### Creating a tensor with `torch.Tensor()`

In [8]:
import torch

describe(torch.Tensor(2,3))

Type:torch.FloatTensor
Shape/size:torch.Size([2, 3])
Values: 
tensor([[5.3482e+22, 1.6987e-07, 2.6846e+23],
        [3.2907e+21, 1.7249e-07, 4.3915e-05]])


### Creating a randomly initialized tensor

In [9]:
import torch

describe(torch.rand(2,3))   # uniform random
describe(torch.randn(2,3))  # normal random

Type:torch.FloatTensor
Shape/size:torch.Size([2, 3])
Values: 
tensor([[0.9806, 0.4036, 0.7936],
        [0.0670, 0.0506, 0.8571]])
Type:torch.FloatTensor
Shape/size:torch.Size([2, 3])
Values: 
tensor([[ 0.9838, -0.6697,  1.4443],
        [-0.7833, -0.9141,  0.0443]])


### Creating a filled tensor

In [12]:
import torch

describe(torch.zeros(2,3))

x = torch.ones(2,3)
describe(x)

x.fill_(5)
describe(x)

Type:torch.FloatTensor
Shape/size:torch.Size([2, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Type:torch.FloatTensor
Shape/size:torch.Size([2, 3])
Values: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Type:torch.FloatTensor
Shape/size:torch.Size([2, 3])
Values: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])


### Creating and initialising a tensor from lists

In [13]:
x = torch.Tensor([[1, 2, 3],
                  [4, 5, 6]])
describe(x)                  

Type:torch.FloatTensor
Shape/size:torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


### Creating and initialising a tensor from Numpy

In [15]:
import torch
import numpy as np

npy = np.random.rand(2,3)
describe(torch.from_numpy(npy))

Type:torch.DoubleTensor
Shape/size:torch.Size([2, 3])
Values: 
tensor([[0.5401, 0.9993, 0.0777],
        [0.6996, 0.2525, 0.2630]], dtype=torch.float64)


## Tensor Slicing, Indexing and Joining

In [1]:
import torch
from functions import describe

x = torch.arange(6).view(2,3)
describe(x)

Type:torch.LongTensor
Shape/size:torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


### Contiguous Indexing using `[:a, :b]`

The code below accesses up to row 1 but not including row 1, and up to col 2, but no including col 2.

In [2]:
describe(x[:1, :2])

Type:torch.LongTensor
Shape/size:torch.Size([1, 2])
Values: 
tensor([[0, 1]])


### Noncontiguous Indexing

Using function `torch.index_select()`, the code below accesses column (`dim=1`) indexed by 0 and 2. 

In [4]:
indices = torch.LongTensor([0, 2])
describe(torch.index_select(x, dim=1, index=indices))

Type:torch.LongTensor
Shape/size:torch.Size([2, 2])
Values: 
tensor([[0, 2],
        [3, 5]])


You can duplicate the same row or column multiple times, by specifying the same index multiple times. 

In [7]:
indices = torch.LongTensor([0, 0, 0])
describe(torch.index_select(x, dim=0, index=indices))

Type:torch.LongTensor
Shape/size:torch.Size([3, 3])
Values: 
tensor([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]])


Use indices directly `[inices_list, indices_list]` can also achieve the same outcome.

In [10]:
row_indices = torch.arange(2).long()
col_indices = torch.LongTensor([0,2])
describe(x[row_indices, col_indices])

Type:torch.LongTensor
Shape/size:torch.Size([2])
Values: 
tensor([0, 5])


In [11]:
describe(x[[0,1], [0,2]])

Type:torch.LongTensor
Shape/size:torch.Size([2])
Values: 
tensor([0, 5])


### Concatenating Tensors

In [12]:
x = torch.arange(6).view(2,3)
describe(x)

Type:torch.LongTensor
Shape/size:torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [13]:
describe(torch.cat([x, x], dim=0))

Type:torch.LongTensor
Shape/size:torch.Size([4, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])


In [14]:
describe(torch.cat([x, x], dim=1))

Type:torch.LongTensor
Shape/size:torch.Size([2, 6])
Values: 
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])


In [15]:
describe(torch.stack([x, x], dim=1))

Type:torch.LongTensor
Shape/size:torch.Size([2, 2, 3])
Values: 
tensor([[[0, 1, 2],
         [0, 1, 2]],

        [[3, 4, 5],
         [3, 4, 5]]])


### Linear Algebra on tensors: multiplication

In [20]:
x1 = torch.arange(6).view(2,3).float()
describe(x1)

Type:torch.FloatTensor
Shape/size:torch.Size([2, 3])
Values: 
tensor([[0., 1., 2.],
        [3., 4., 5.]])


In [21]:
x2 = torch.ones(3,2)
x2[:, 1] += 1
describe(x2)

Type:torch.FloatTensor
Shape/size:torch.Size([3, 2])
Values: 
tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])


In [22]:
describe(torch.mm(x1, x2))

Type:torch.FloatTensor
Shape/size:torch.Size([2, 2])
Values: 
tensor([[ 3.,  6.],
        [12., 24.]])


## CUDA tensors

In [5]:
import torch
from functions import describe

print(torch.cuda.is_available())

True


In [3]:
# prefered method: device agnostic tensor instantiation

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)


cuda


In [8]:
x = torch.rand(3,2).to(device)
describe(x)

Type:torch.cuda.FloatTensor
Shape/size:torch.Size([3, 2])
Values: 
tensor([[0.1458, 0.3894],
        [0.0080, 0.8904],
        [0.9691, 0.2905]], device='cuda:0')


```{warning}
Mixing CUDA tensors with CPU-bound tensors will lead to errors. This is because we need to ensure the tensors are on the same device. 
```

In [9]:
y = torch.rand(3,2)
x + y

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [11]:
cpu_device = torch.device("cpu")
x = x.to(cpu_device)
y = y.to(cpu_device)
x + y

tensor([[0.6276, 0.9583],
        [0.7592, 1.2605],
        [1.0946, 0.9480]])

```{note}
It is expensive to move data back and forth from the GPU. Best practice is to carry out as much computation on GPU as possible and then just transfering the final results to CPU. 
```

```{warning}
`torch.arange()` creates LongTensor, for `torch.mm()`, we need to convert the LongTensor to FloatTensor by using `x.float()`.
```