Tensor Operations
=================

## Addition

In [4]:
import torch
from functions import describe
x = torch.randn(2,3)
describe(x)

Type:torch.FloatTensor
Shape/size:torch.Size([2, 3])
Values: 
tensor([[-0.7697,  1.3831,  0.7184],
        [-2.2645,  0.4363,  1.7446]])


In [5]:
describe(torch.add(x,x))

Type:torch.FloatTensor
Shape/size:torch.Size([2, 3])
Values: 
tensor([[-1.5394,  2.7661,  1.4369],
        [-4.5290,  0.8725,  3.4892]])


In [6]:
describe(x + x)

Type:torch.FloatTensor
Shape/size:torch.Size([2, 3])
Values: 
tensor([[-1.5394,  2.7661,  1.4369],
        [-4.5290,  0.8725,  3.4892]])


## Dimension based tensor operations

In [8]:
x = torch.arange(6)
describe(x)


Type:torch.LongTensor
Shape/size:torch.Size([6])
Values: 
tensor([0, 1, 2, 3, 4, 5])


In [9]:
x = x.view(2,3)
describe(x)

Type:torch.LongTensor
Shape/size:torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [10]:
describe(torch.sum(x, dim=0))

Type:torch.LongTensor
Shape/size:torch.Size([3])
Values: 
tensor([3, 5, 7])


In [11]:
describe(torch.sum(x, dim=1))

Type:torch.LongTensor
Shape/size:torch.Size([2])
Values: 
tensor([ 3, 12])


In [12]:
describe(torch.transpose(x, 0, 1))

Type:torch.LongTensor
Shape/size:torch.Size([3, 2])
Values: 
tensor([[0, 3],
        [1, 4],
        [2, 5]])
