Types of Tensor
=================

## A helper function `describe(x)`
`x` is a torch tensor

NOTE: `tensor.shape` is a property, not a callable function

In [2]:
def describe(x):
    print("Type:{}".format(x.type()))
    print("Shape/size:{}".format(x.shape))
    print("Values: \n{}".format(x))


## Creating a tensor with `torch.Tensor()`

In [3]:
import torch

describe(torch.Tensor(2,3))

Type:torch.FloatTensor
Shape/size:torch.Size([2, 3])
Values: 
tensor([[1.3311e+22, 4.2769e-05, 2.0890e+20],
        [4.3920e-05, 4.2426e-08, 5.3832e+22]])


## Creating a randomly initialized tensor

In [9]:
import torch

describe(torch.rand(2,3))   # uniform random
describe(torch.randn(2,3))  # normal random

Type:torch.FloatTensor
Shape/size:torch.Size([2, 3])
Values: 
tensor([[0.9806, 0.4036, 0.7936],
        [0.0670, 0.0506, 0.8571]])
Type:torch.FloatTensor
Shape/size:torch.Size([2, 3])
Values: 
tensor([[ 0.9838, -0.6697,  1.4443],
        [-0.7833, -0.9141,  0.0443]])


## Creating a filled tensor

In [12]:
import torch

describe(torch.zeros(2,3))

x = torch.ones(2,3)
describe(x)

x.fill_(5)
describe(x)

Type:torch.FloatTensor
Shape/size:torch.Size([2, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Type:torch.FloatTensor
Shape/size:torch.Size([2, 3])
Values: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Type:torch.FloatTensor
Shape/size:torch.Size([2, 3])
Values: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])


## Creating and initialising a tensor from lists

In [13]:
x = torch.Tensor([[1, 2, 3],
                  [4, 5, 6]])
describe(x)                  

Type:torch.FloatTensor
Shape/size:torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


## Creating and initialising a tensor from Numpy

In [15]:
import torch
import numpy as np

npy = np.random.rand(2,3)
describe(torch.from_numpy(npy))

Type:torch.DoubleTensor
Shape/size:torch.Size([2, 3])
Values: 
tensor([[0.5401, 0.9993, 0.0777],
        [0.6996, 0.2525, 0.2630]], dtype=torch.float64)
