Tensor Slicing, Indexing and Joining
====================================

In [1]:
import torch
from functions import describe

x = torch.arange(6).view(2,3)
describe(x)

Type:torch.LongTensor
Shape/size:torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


## Contiguous Indexing using `[:a, :b]`

The code below accesses up to row 1 but not including row 1, and up to col 2, but no including col 2.

In [2]:
describe(x[:1, :2])

Type:torch.LongTensor
Shape/size:torch.Size([1, 2])
Values: 
tensor([[0, 1]])


## Noncontiguous Indexing

Using function `torch.index_select()`, the code below accesses column (`dim=1`) indexed by 0 and 2. 

In [4]:
indices = torch.LongTensor([0, 2])
describe(torch.index_select(x, dim=1, index=indices))

Type:torch.LongTensor
Shape/size:torch.Size([2, 2])
Values: 
tensor([[0, 2],
        [3, 5]])


You can duplicate the same row or column multiple times, by specifying the same index multiple times. 

In [7]:
indices = torch.LongTensor([0, 0, 0])
describe(torch.index_select(x, dim=0, index=indices))

Type:torch.LongTensor
Shape/size:torch.Size([3, 3])
Values: 
tensor([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]])


Use indices directly `[inices_list, indices_list]` can also achieve the same outcome.

In [10]:
row_indices = torch.arange(2).long()
col_indices = torch.LongTensor([0,2])
describe(x[row_indices, col_indices])

Type:torch.LongTensor
Shape/size:torch.Size([2])
Values: 
tensor([0, 5])


In [11]:
describe(x[[0,1], [0,2]])

Type:torch.LongTensor
Shape/size:torch.Size([2])
Values: 
tensor([0, 5])


## Concatenating Tensors

In [12]:
x = torch.arange(6).view(2,3)
describe(x)

Type:torch.LongTensor
Shape/size:torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [13]:
describe(torch.cat([x, x], dim=0))

Type:torch.LongTensor
Shape/size:torch.Size([4, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])


In [14]:
describe(torch.cat([x, x], dim=1))

Type:torch.LongTensor
Shape/size:torch.Size([2, 6])
Values: 
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])


In [15]:
describe(torch.stack([x, x], dim=1))

Type:torch.LongTensor
Shape/size:torch.Size([2, 2, 3])
Values: 
tensor([[[0, 1, 2],
         [0, 1, 2]],

        [[3, 4, 5],
         [3, 4, 5]]])


In [ ]:
## Linear Algebra on tensors: multiplication

In [20]:
x1 = torch.arange(6).view(2,3).float()
describe(x1)

Type:torch.FloatTensor
Shape/size:torch.Size([2, 3])
Values: 
tensor([[0., 1., 2.],
        [3., 4., 5.]])


In [21]:
x2 = torch.ones(3,2)
x2[:, 1] += 1
describe(x2)

Type:torch.FloatTensor
Shape/size:torch.Size([3, 2])
Values: 
tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])


In [22]:
describe(torch.mm(x1, x2))

Type:torch.FloatTensor
Shape/size:torch.Size([2, 2])
Values: 
tensor([[ 3.,  6.],
        [12., 24.]])


```{warning}
`torch.arange()` creates LongTensor, for `torch.mm()`, we need to convert the LongTensor to FloatTensor by using `x.float()`.
```